- name: Create the "{{ vars[cluster_type + '_database_user'] }}" role
  postgresql_user:
    login_host:      "{{ control_database_host }}"
    login_password:  "{{ vars[cluster_type + '_db_admin_password'] | b64decode }}"
    name:            "{{ vars[cluster_type + '_database_user'] }}"
    password:        "{{ vars[cluster_type + '_db_user_password'] | b64decode }}"
    role_attr_flags: CREATEROLE

- name: Create the "{{ concent_versions[concent_version][cluster_type + '_database_name'] | default(vars[cluster_type + '_database_name']) }}" database
  postgresql_db:
    login_host:      "{{ control_database_host }}"
    login_password:  "{{ vars[cluster_type + '_db_admin_password'] | b64decode }}"
    name:            "{{ concent_versions[concent_version][cluster_type + '_database_name'] | default(vars[cluster_type + '_database_name']) }}"
    owner:           postgres

- name: Grant "{{ vars[cluster_type + '_database_user'] }}" role all privileges for the "{{ concent_versions[concent_version][cluster_type + '_database_name'] | default(vars[cluster_type + '_database_name']) }}" database
  postgresql_privs:
    login_host:      "{{ control_database_host }}"
    login_password:  "{{ vars[cluster_type + '_db_admin_password'] | b64decode }}"
    db:              "{{ concent_versions[concent_version][cluster_type + '_database_name'] | default(vars[cluster_type + '_database_name']) }}"
    role:            "{{ vars[cluster_type + '_database_user'] }}"
    type:            database
    objs:            "{{ concent_versions[concent_version][cluster_type + '_database_name'] | default(vars[cluster_type + '_database_name']) }}"
    privs:           ALL

- name: Grant postgres all the privileges of the "{{ vars[cluster_type + '_database_user'] }}" role
  postgresql_privs:
    login_host:      "{{ control_database_host }}"
    login_password:  "{{ vars[cluster_type + '_db_admin_password'] | b64decode }}"
    db:              "{{ concent_versions[concent_version][cluster_type + '_database_name'] | default(vars[cluster_type + '_database_name']) }}"
    type:            group
    objs:            "{{ vars[cluster_type + '_database_user'] }}"
    roles:           postgres

- name: Change owner of `public` schema to the "{{ vars[cluster_type + '_database_user'] }}" role
  postgresql_schema:
    login_user:      postgres
    login_host:      "{{ control_database_host }}"
    login_password:  "{{ vars[cluster_type + '_db_admin_password'] | b64decode }}"
    database:        "{{ concent_versions[concent_version][cluster_type + '_database_name'] | default(vars[cluster_type + '_database_name']) }}"
    name:            public
    owner:           "{{ vars[cluster_type + '_database_user'] }}"
