- name: Delete the "{{ vars[ cluster_type + '_database_name'] }}" database
  postgresql_db:
    login_host:      "{{ control_database_host }}"
    login_password:  "{{ control_db_admin_password | b64decode }}"
    state:           absent
    name:            "{{ vars[ cluster_type + '_database_name'] }}"
    owner:           postgres

- name: Delete the "{{ vars[ cluster_type + '_database_user'] }}" role for manage "{{ vars[ cluster_type + '_database_name'] }}" database
  postgresql_user:
    login_host:      "{{ control_database_host }}"
    login_password:  "{{ control_db_admin_password | b64decode }}"
    state:           absent
    name:            "{{ vars[ cluster_type + '_database_user'] }}"
    password:        "{{ vars[ cluster_type + '_db_user_password'] | b64decode }}"
    role_attr_flags: CREATEROLE

